### ISSUE TITLE
Building LibreSSL from source does not work

### ISSUE THREAD

**Issue by zenith391** [haze/zig-libressl#3]
Using `useLibreSslForStep` without using the system libre ssl does not work at all. I've encountered this bug trying to use [zelda](https://github.com/haze/zelda) and it doesn't seem to be an isolate case given the CI also can't build for this same reason: https://github.com/haze/zelda/actions/runs/3166303700/jobs/5155925710

**Comment by haze** [comment]
macOS works, but I think I'm missing some Linux specific parts. I don't have a linux machine so this might take a second to fix, but I am working on it. Thanks!

**Comment by haze** [comment]
@zenith391 can you try and test with HEAD?

**Comment by zenith391** [comment]
Just tried on Linux. It works now! Thanks you
